### ISSUE TITLE
type to filter results

### ISSUE THREAD

**Issue by ergelo** [trietsch/alfred-bluetooth-connector#2]
It would be great if it were possible to filter results as you type. e.g. if I wanted to select a device called 'headphones' I could type 'blt he' and press enter, instead of 'blt' down arrow down arrow down arrow enter.

**Comment by trietsch** [comment]
Nice idea! I'll see if I can change that. PRs are welcome as well :)

**Comment by jsadeli** [comment]
Had the same need, but you can try enabling Alfred's built-in search filter (modify the workflow).
https://www.alfredapp.com/help/workflows/inputs/script-filter/#alfred-filters-results

Note: Unfortunately, Alfred's built-in filter doesn't support fuzzy search. i.e. searching "tooth" will not show up for "My Bluetooth Device", but searching "Bluetooth" or "Device" will work.

**Comment by trietsch** [comment]
@ergelo @jsadeli fixed in [v0.1.1](https://github.com/trietsch/alfred-bluetooth-connector/releases/tag/v0.1.1), also implemented auto-updating, to enable easy future updates.

**Comment by jsadeli** [comment]
👍
