### ISSUE TITLE
Error when attempting to run

### ISSUE THREAD

**Issue by MarellaB** [trietsch/alfred-bluetooth-connector#4]
As soon as I type "blt A" or any other character after the space I get an error as follows:

`"Error in workflow 'Bluetooth Device Connector'`
`'ascii' codec can't decode byte 0xe2 in position 15: ordinal not in range(128)`

![image](https://user-images.githubusercontent.com/10491114/53779759-6549d280-3ecf-11e9-9cdf-d11cc6b27a28.png)

**Comment by trietsch** [comment]
Hi, you can use https://github.com/tilmanginzel/alfred-bluetooth-workflow 
I've collaborated with another developer to create a better one with more features.
