### ISSUE TITLE
Notification says the device is connected while it's not.

### ISSUE THREAD

**Issue by tbrek** [trietsch/alfred-bluetooth-connector#5]
Steps to reproduce:

1. Try connecting to device which is out of range or currently connected other device
2. Notification will say it's connected while it isn't

**Comment by trietsch** [comment]
Hi @tbrek, please use [alfred-bluetooth-workflow](https://github.com/tilmanginzel/alfred-bluetooth-workflow) instead, it's got more functionality and I've merged the work of this repo to that repo.

**Comment by tbrek** [comment]
I have just installed it, same issue:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/9820995/67945248-5c341100-fbd6-11e9-89ec-13788ff74154.png">

Got this for device which isn't here.

**Comment by trietsch** [comment]
@tilmanginzel does this sound familiar to you? I think I remember an issue that also talked about devices saying they're connected, while they're not.
@tbrek might be better to transfer this issue to [alfred-bluetooth-workflow](https://github.com/tilmanginzel/alfred-bluetooth-workflow)

**Comment by tilmanginzel** [comment]
Hi @tbrek, @trietsch, I created an issue in [alfred-bluetooth-workflow](https://github.com/tilmanginzel/alfred-bluetooth-workflow)

Let's continue there :)
